//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WuzzufnyAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client
    {
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public string Address { get; set; }
        public string Image { get; set; }
        public string Mobile { get; set; }
        public string JobRole { get; set; }
        public string Cv { get; set; }
        public string LinkedIn { get; set; }
        public string Facebook { get; set; }
        public string Governorate { get; set; }
        public string City { get; set; }
        public string Password { get; set; }
        public string ConfirmPassword { get; set; }
        public string PasswordResetToken { get; set; }
        public string UserType { get; set; }
        public Nullable<int> CountryId { get; set; }
        public System.DateTime TokenDate { get; set; }
        public bool IsEnable { get; set; }
        public string PlayerId { get; set; }
    }
}
